/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilDuzenleRouteImport } from './routes/profil-duzenle'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OdakRouteImport } from './routes/odak'
import { Route as IstatistikRouteImport } from './routes/istatistik'
import { Route as GorevlerRouteImport } from './routes/gorevler'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as IndexRouteImport } from './routes/index'

const ProfilDuzenleRoute = ProfilDuzenleRouteImport.update({
  id: '/profil-duzenle',
  path: '/profil-duzenle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OdakRoute = OdakRouteImport.update({
  id: '/odak',
  path: '/odak',
  getParentRoute: () => rootRouteImport,
} as any)
const IstatistikRoute = IstatistikRouteImport.update({
  id: '/istatistik',
  path: '/istatistik',
  getParentRoute: () => rootRouteImport,
} as any)
const GorevlerRoute = GorevlerRouteImport.update({
  id: '/gorevler',
  path: '/gorevler',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
  '/profil': typeof ProfilRoute
  '/profil-duzenle': typeof ProfilDuzenleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
  '/profil': typeof ProfilRoute
  '/profil-duzenle': typeof ProfilDuzenleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
  '/profil': typeof ProfilRoute
  '/profil-duzenle': typeof ProfilDuzenleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayarlar'
    | '/gorevler'
    | '/istatistik'
    | '/odak'
    | '/profil'
    | '/profil-duzenle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayarlar'
    | '/gorevler'
    | '/istatistik'
    | '/odak'
    | '/profil'
    | '/profil-duzenle'
  id:
    | '__root__'
    | '/'
    | '/ayarlar'
    | '/gorevler'
    | '/istatistik'
    | '/odak'
    | '/profil'
    | '/profil-duzenle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  GorevlerRoute: typeof GorevlerRoute
  IstatistikRoute: typeof IstatistikRoute
  OdakRoute: typeof OdakRoute
  ProfilRoute: typeof ProfilRoute
  ProfilDuzenleRoute: typeof ProfilDuzenleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil-duzenle': {
      id: '/profil-duzenle'
      path: '/profil-duzenle'
      fullPath: '/profil-duzenle'
      preLoaderRoute: typeof ProfilDuzenleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odak': {
      id: '/odak'
      path: '/odak'
      fullPath: '/odak'
      preLoaderRoute: typeof OdakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istatistik': {
      id: '/istatistik'
      path: '/istatistik'
      fullPath: '/istatistik'
      preLoaderRoute: typeof IstatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gorevler': {
      id: '/gorevler'
      path: '/gorevler'
      fullPath: '/gorevler'
      preLoaderRoute: typeof GorevlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  GorevlerRoute: GorevlerRoute,
  IstatistikRoute: IstatistikRoute,
  OdakRoute: OdakRoute,
  ProfilRoute: ProfilRoute,
  ProfilDuzenleRoute: ProfilDuzenleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
