/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GorevlerRouteImport } from './routes/gorevler'
import { Route as IndexRouteImport } from './routes/index'

const GorevlerRoute = GorevlerRouteImport.update({
  id: '/gorevler',
  path: '/gorevler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gorevler'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gorevler'
  id: '__root__' | '/' | '/gorevler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GorevlerRoute: typeof GorevlerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gorevler': {
      id: '/gorevler'
      path: '/gorevler'
      fullPath: '/gorevler'
      preLoaderRoute: typeof GorevlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GorevlerRoute: GorevlerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
