/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OdakRouteImport } from './routes/odak'
import { Route as IstatistikRouteImport } from './routes/istatistik'
import { Route as GorevlerRouteImport } from './routes/gorevler'
import { Route as IndexRouteImport } from './routes/index'

const OdakRoute = OdakRouteImport.update({
  id: '/odak',
  path: '/odak',
  getParentRoute: () => rootRouteImport,
} as any)
const IstatistikRoute = IstatistikRouteImport.update({
  id: '/istatistik',
  path: '/istatistik',
  getParentRoute: () => rootRouteImport,
} as any)
const GorevlerRoute = GorevlerRouteImport.update({
  id: '/gorevler',
  path: '/gorevler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gorevler': typeof GorevlerRoute
  '/istatistik': typeof IstatistikRoute
  '/odak': typeof OdakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gorevler' | '/istatistik' | '/odak'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gorevler' | '/istatistik' | '/odak'
  id: '__root__' | '/' | '/gorevler' | '/istatistik' | '/odak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GorevlerRoute: typeof GorevlerRoute
  IstatistikRoute: typeof IstatistikRoute
  OdakRoute: typeof OdakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/odak': {
      id: '/odak'
      path: '/odak'
      fullPath: '/odak'
      preLoaderRoute: typeof OdakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/istatistik': {
      id: '/istatistik'
      path: '/istatistik'
      fullPath: '/istatistik'
      preLoaderRoute: typeof IstatistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gorevler': {
      id: '/gorevler'
      path: '/gorevler'
      fullPath: '/gorevler'
      preLoaderRoute: typeof GorevlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GorevlerRoute: GorevlerRoute,
  IstatistikRoute: IstatistikRoute,
  OdakRoute: OdakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
